### ISSUE TITLE
Raisecloud not recognizing if printer is disconnected from octo then reconnected

### ISSUE THREAD

**Issue by Kokorone** [Raise3D/Octoprint-Raisecloud#2]
I have my printer linked to raisecloud with octo, and it prints perfectly well from raisecloud until I power off my printer, disconnecting it from octo. While the printer is in the "off" state, raisecloud thinks its still in standby, and when I manually reconnect the printer in octo then start a print with raisecloud, nothing will happen until octoprint is restarted. 

Here is the steps broken down
1. Link printer with raisecloud
2. Print something
3. Turn off printer, disconnecting it from octo
4. Observe that raisecloud still sees printer as in standby
5. Turn printer back on, reconnect it to octo
6. Attempt to send a print to the printer with raisecloud
7. Observe the printer not receive anything or attempt to print

**Comment by irinecan** [comment]
Thank you for the feedback. We have already tested it but the issue did not persist. Could you please export the log of Octoprint so that we can check the issue? You can also email us: Raise Cloud Support<raisecloud@raise3d.com>
Best

**Comment by Allram** [comment]
I have the exact same problem. I will send the Octoprint log later on.

**Comment by Kokorone** [comment]
So right now, I've turned off my printer and turned it back on since my last raisecloud print. Raisecloud is reporting this. 
![image](https://user-images.githubusercontent.com/32761171/86829172-f4797400-c048-11ea-91af-6a7d9d523d66.png)

**Comment by Kokorone** [comment]
If I go to the files tab and select another file to print, and select the printer, it is still showing as done, despite it not being connected to octo yet. 
![image](https://user-images.githubusercontent.com/32761171/86829276-14109c80-c049-11ea-8948-a03318f7b262.png)

At this point I reconnect my printer with octo and then hit start on print and I get this popup
![image](https://user-images.githubusercontent.com/32761171/86829368-2c80b700-c049-11ea-8b46-b8dfedf63c14.png)

From here I look at my octo window and nothing is happening
![image](https://user-images.githubusercontent.com/32761171/86829406-3a363c80-c049-11ea-8bee-daa110a4be7c.png)

If I look at the printer tab in RaiseCloud, the status is still reading done on the previous print, and the print is sitting in jobs not being executed. 
![image](https://user-images.githubusercontent.com/32761171/86829532-5cc85580-c049-11ea-9306-eed4606aaf82.png)

**Comment by irinecan** [comment]
> I have the exact same problem. I will send the Octoprint log later on.

Thank you for the feedback, we will work on it once we received the log.

**Comment by irinecan** [comment]
> I have the exact same problem. I will send the Octoprint log later on.

Thank you for the feedback, we will work on it once we received the log.

> If I go to the files tab and select another file to print, and select the printer, it is still showing as done, despite it not being connected to octo yet.
> ![image](https://user-images.githubusercontent.com/32761171/86829276-14109c80-c049-11ea-8948-a03318f7b262.png)
> 
> At this point I reconnect my printer with octo and then hit start on print and I get this popup
> ![image](https://user-images.githubusercontent.com/32761171/86829368-2c80b700-c049-11ea-8b46-b8dfedf63c14.png)
> 
> From here I look at my octo window and nothing is happening
> ![image](https://user-images.githubusercontent.com/32761171/86829406-3a363c80-c049-11ea-8bee-daa110a4be7c.png)
> 
> If I look at the printer tab in RaiseCloud, the status is still reading done on the previous print, and the print is sitting in jobs not being executed.
> ![image](https://user-images.githubusercontent.com/32761171/86829532-5cc85580-c049-11ea-9306-eed4606aaf82.png)

So you caught a power loss when you finish the print without choose the "Success" nor "Failure". This is a bug of RaiseCloud and we already debug it. Will be released in the next version. 
Thank you for your patience :)
