### ISSUE TITLE
sd card access 

### ISSUE THREAD

**Issue by Jonijakob** [Raise3D/Octoprint-Raisecloud#3]
hi
I am trying to figure out how to access the sd card this is possible?

**Comment by irinecan** [comment]
> hi
> I am trying to figure out how to access the sd card this is possible?

Thank you for the question. We wonder more info so that we can know how we can help. Are you using the sd card for printing cause you have some private model that can not be shared?

**Comment by Jonijakob** [comment]
I am uploading always the models to the sd card (wifi sd) and not to the octo pi server, and when I want to control the printer it not give me any access to the sd card and show the models inside, but show only the local files in the octoprint server storage, it will be amazing to gets access to the sd card too and use it ...

**Comment by irinecan** [comment]
> I am uploading always the models to the sd card (wifi sd) and not to the octo pi server, and when I want to control the printer it not give me any access to the sd card and show the models inside, but show only the local files in the octoprint server storage, it will be amazing to gets access to the sd card too and use it ...

Thank you for the feedback. We will add it to the dev plan and check the accessibility of it.

**Comment by Raise3D** [comment]
SD card for printing makes plugin out of control
