### ISSUE TITLE
RaiseCloud/Octoprint stuck at "Receiving Job"

### ISSUE THREAD

**Issue by evolwun** [Raise3D/Octoprint-Raisecloud#4]
For the last week+, I have been unable to send jobs to printers attached to RaiseCloud via RaiseOcto. It just sits in "Receiving Job". There is nothing I can do at that point other than reset the Octoprint software. I have heard from multiple other people that they are experiencing the same issue. I have tried giving it time to transfer the job. But after a couple hours, I am pretty sure it is not a "please wait" type of solution.
![Annotation 2020-08-06 095431](https://user-images.githubusercontent.com/18053846/89796743-daff9800-dade-11ea-8d43-3fa937c7d13b.jpg)

**Comment by evolwun** [comment]
Newest version (1.1.0) did not fix this.

Edit: Uninstalling and reinstalling the plugin fixed the issues. Please do not have the plugin prompt to reinstall if it is not the proper way to install it.

**Comment by Raise3D** [comment]
RaiseCloud has fixed this
